spring.application.name=itl-incident-management

spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/incident_db}
spring.datasource.username=${JDBC_DATABASE_USERNAME:incident_user}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:incident_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


spring.mvc.format.date-time=iso

server.port=8080

jwt.secret=itl-incident-management-jwt-secret-key-for-dev-only-change-in-prod
jwt.expiration-ms=86400000

itl.sla.scheduler.enabled=true
itl.sla.scheduler.initial-delay-ms=60000
itl.sla.scheduler.fixed-delay-ms=300000
